### ISSUE TITLE
Academicons

### ISSUE THREAD

**Issue by helderc** [privefl/rmarkdown-website-template#10]
Thanks for the template, it works very well!

Is it possible to use Academicons [1]?
I tried a couple of things but nothing works.
Thanks again.

[1] https://jpswalsh.github.io/academicons/

**Comment by privefl** [comment]
Not sure but you might be able to get your own images as icons, following https://bookdown.org/yihui/rmarkdown-cookbook/favicon.html.

**Comment by privefl** [comment]
What I've tested so far didn't work.
If you find a solution, I would be interested to know.

**Comment by helderc** [comment]
Sure, I did it following the link you posted!

The only difference is that inside the `header.html` I put:

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css">`

To help others, here is how my `_site.yml` looks like:

```
name: "Statistik"                                # CHANGE HERE 
output_dir: "."
navbar:
  title: "Statistik"                             # CHANGE HERE 
  type: inverse
  left:
    - text: "Home"
      icon: fa-home
      href: index.html
    - text: "About"
      icon: fa-user 
      href: about.html
  right:
    - icon: "fa-envelope fa-2x"
      href: mailto:heldercro@gmail.com
    - icon: "ai-google-scholar ai-2x"
      href: https://scholar.google.com/citations?user=2M2ZAswAAAAJ
    - icon: "fa-github fa-2x"
      href: https://github.com/heldercro
    - icon: "ai-researchgate ai-2x"
      href: https://www.researchgate.net/profile/Helder-Oliveira-4
    - icon: "ai-orcid ai-2x"
      href: https://orcid.org/0000-0003-4558-2844
    - icon: "fa-linkedin fa-2x"
      href: https://www.linkedin.com/in/heldercro/
    
output:
  html_document:
    theme: flatly
    highlight: textmate
    includes:
      in_header: header.html

```

For this page: https://statistik.netlify.app

Thanks again!
